### ISSUE TITLE
[BUG] Console spam command

### ISSUE THREAD

**Issue by shaqupl** [AyushDev03/GlobalExecute#1]
When use command "_gexecute all say test_" in console it spams 17 times:
![image](https://user-images.githubusercontent.com/68109218/106729556-e48d3700-660d-11eb-8fed-560b8d4e3444.png)

**Comment by ayush03dev** [comment]
The issue has been fixed with the latest update. The plugin now implements websocket protocol instead of messaging channels for communication with other servers.
